packages:
  - packages/*
  - apps/*
allowBuilds:
  esbuild: true
  msgpackr-extract: true
catalogs:
  cli:
    colorette: ^2.0.20
    empathic: ^2.0.1
    fast-glob: ^3.3.3
    yaml: ^2.9.1
  core:
    "@effect/platform-node": 4.0.0-beta.107
    "@effect/vitest": 4.0.0-beta.107
    "@total-typescript/tsconfig": ^1.0.4
    "@types/node": ^26.4.0
    effect: 4.0.0-beta.107
    oxlint: ^1.80.0
    rolldown: ^1.2.6
    typescript: ^7.0.2
    vitest: ^4.1.11
  lsp:
    vscode-languageserver-protocol: ^3.18.3
    vscode-languageserver-textdocument: ^1.0.14
    vscode-languageserver-types: ^3.18.3
